/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_monster_airgesture_PhaseProcessI */

#ifndef _Included_com_example_monster_airgesture_PhaseProcessI
#define _Included_com_example_monster_airgesture_PhaseProcessI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_com_example_monster_airgesture_PhaseProcessI_createNativePhaseProcess
 * Method:    createNativePhaseProcess
 * Signature: (IIFF)J
 */
JNIEXPORT jlong JNICALL Java_com_example_monster_airgesture_PhaseProcessI_createNativeSignalProcess
        (JNIEnv *, jobject);


JNIEXPORT jfloat JNICALL Java_com_example_monster_airgesture_PhaseProcessI_doActionRecognitionV3
        (JNIEnv *, jobject,  jlong, jshortArray, jint, jstring j_str, jstring j_str2, jint sensitive);


JNIEXPORT jfloat JNICALL Java_com_example_monster_airgesture_PhaseProcessI_doInit
        (JNIEnv *, jobject,  jlong, jstring j_str);

#ifdef __cplusplus
}
#endif
#endif
